# Generated by Django 5.2.4 on 2026-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='Food_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
