# Generated by Django 5.2.4 on 2026-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_fooditem_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
