# Generated by Django 5.2.4 on 2026-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='food',
            field=models.TextField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
