# Generated by Django 5.2.4 on 2026-02-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_orders_food'),
        ('Restaurant', '0004_alter_fooditem_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Total_price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='orders',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.fooditem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('OUT_OF_DELIVERY', 'Out of Delivery'), ('DELIVERED', 'Delivered')], default='PLACED', max_length=30),
        ),
    ]
