# Generated by Django 5.2.4 on 2026-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_rename_create_at_orders_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('OUT_OF_DELIVERY', 'Out of Delivery'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PLACED', max_length=30),
        ),
    ]
