# Generated by Django 5.2.4 on 2026-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_add_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
