# Generated by Django 5.2.4 on 2026-02-26 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_add_to_cart_quantity'),
        ('Restaurant', '0004_alter_fooditem_food_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_to_cart',
            new_name='cart',
        ),
    ]
