# Generated by Django 5.2.4 on 2026-03-04 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_rename_add_to_cart_cart'),
        ('Restaurant', '0004_alter_fooditem_food_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='MyCart',
        ),
    ]
